export const Endpoints = {
    GET_MERCHANT_OTP: 'get-merchant-otp',
    LIST_CAT_SUBCAT: 'list-category-subcategory',
    REGISTER_MERCHANT: 'register-merchant',
    LOGIN_MERCHANT: 'get-merchant-token',
    RESET_PASSCODE: 'reset-passcode',
    GET_APPOINTMENTS: 'getAllAppointments',
    GET_ALL_REEDEMS: 'get-all-reedem',
    REEDEM_CODE: 'updateReedemed',
    ADD_SERVICE_CATEGORY: 'add-service-category',
    ADD_SERVICE_SUBCATEGORY: 'add-service-subCategory',
    ADD_SERVICE: 'add-service',
    SERVICE_CAT_SUBCAT: 'list-servicecategory-servicesubcategory',
    ACCOUNT_DETAILS: 'merchant/get-own-businesses',
    GET_ALL_SERVICES: 'get-services?includeOfflineServices=true',
    UPDATE_MERCHANT: 'update-merchant',
    GET_SALES_DETAILS: 'getAllSalesDetail',
};
