export const Keys = {
    SEND_OTP: 'send_otp',
    GET_CATEGORIES: 'get_category_list',
    REGISTER_MERCHANT: 'register_merchant',
    LOGIN_MERCHANT: 'login_merchant',
    RESET_PASSCODE: 'reset_passcode',
    GET_APPOINTMENTS: 'get_appointments',
    GET_ALL_REEDEMS: 'get-all-reedems',
    GET_CATEGORY_SUBCATEGORY: 'get-category-subcategory',
    REEDEM_CODE: 'reedem-code',
    ADD_SERVICE_CATEGORY: 'add-service-category',
    ADD_SERVICE_SUBCATEGORY: 'add-service-subcategory',
    ADD_SERVICE: 'add-service',
    SERVICE_CAT_SUBCAT: 'list-servicecategory-servicesubcategory',
    ACCOUNT_DETAILS: 'get-account-details',
    GET_ALL_SERVICES: 'get-all-services',
    UPDATE_MERCHANT: 'update-merchant',
};
